### ISSUE TITLE
Simplify the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [myasinK/prj-rev-bwfs-dasmoto#6]
It is usually a good idea to simplify the CSS code when multiple elements share the same property and value. When you added the font-family property for the body selector, all elements nested in the body tag in HTML will also inherit the property, so there is no need to add the property to each selector individually. In addition, you can probably add the font-weight to the body as well, and remove the property from each selector individually, like so

```css
body {
  font-family: Helvetica;
  font-weight: bold;
}
```
